### PR TITLE
[meta] add repl.it to issue template

### PR DESCRIPTION
**Pull request by blainekasten**
👏 👏 👏 👏 👏  @amasad and the team at Repl have created for us an online repl we can use for support issues! 👏 👏 👏 👏 👏 

@ljharb I hope this helps!

https://repl.it/languages/enzyme

We can also embed it on our docs if we want?
https://repl.it/site/docs/embed

### CODE REVIEW

**Comment by ljharb** [comment]
Interesting - how would it handle various babel and flow settings?

**Comment by blainekasten** [comment]
@ljharb how does babel and flow settings relate to this? This is just a tool we can use to request minimal reproducible cases for bugs.

I'm not imagining people dump their code in there. But instead give us a real scenario illustrating a bug

**Comment by nfcampos** [comment]
@blainekasten this is very cool indeed!
which version of enzyme does that run?

**Comment by nfcampos** [comment]
and would it be possible to have jsdom loaded by default, otherwise it doesnt work when you use mount?

**Comment by blainekasten** [comment]
@nfcampos good call. I'll ping amjad

**Comment by amasad** [comment]
yeah we can pre-load jsdom (automagically in the background). What's the code for that?

**Comment by nfcampos** [comment]
https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md

**Comment by ljharb** [comment]
@blainekasten everything that prevents people from pasting their code directly is going to be an obstacle; i'd prefer it if this repl supported flow, class properties, decorators, etc, just to avoid that kind of problem.

@amasad thanks for your help! Is there any way (git, perhaps?) that enzyme contributors would be able to update the various settings in that repl moving forward, so we don't have to bother you?

**Comment by amasad** [comment]
>@amasad thanks for your help! Is there any way (git, perhaps?) that enzyme contributors would be able to update the various settings in that repl moving forward, so we don't have to bother you?

@ljharb happy to help! Yeah so we have something in the works that would allow us to open source our images and have folks contribute or even own and publish their environments on Repl.it. Hopefully will have more to say in the next couple of months

**Comment by amasad** [comment]
Hey I updated the implementation a while ago but forgot to update this issue. `mount` works now

**Comment by ljharb** [comment]
@amasad thanks! what about supporting all the stage 0+ babel transforms? Also, any update on us being able to make updates to the image?

**Comment by amasad** [comment]
@ljharb it's still in the works -- lots of infra issues especially around security to deal with. 

Re stage 0 transforms -- will add that.

**Comment by ljharb** [comment]
@amasad hi! have there been any updates?

**Comment by ljharb** [comment]
@amasad ping :-) any updates?

**Comment by ljharb** [comment]
@amasad howdy! any update?

**Comment by amasad** [comment]
Hey @ljharb! Sorry for the delay. I think we now have enough flexibility that you can just create a "base" repl as opposed to a "language" or an image. I think it's a much better UX this way. 

Here, I've created that repl complete with .babelrc:

- https://repl.it/@amasad/enzyme-playground
- connected to this repo: https://repl.it/@amasad/enzyme-playground

Just have your users fork that repl and create issues and test cases. 

The only downside which will be solved soon is the initial install step. We're introducing pretty aggressive snapshot-based caching soon. We're already testing it and it's working really well.

Let me know what you think!

**Comment by amasad** [comment]
@ljharb excited to hear what you think!

**Comment by ljharb** [comment]
@amasad thanks for the reply :-) this looks great. any chance it can be connected to a subfolder in an existing repo, namely, in this one? That way we can host the repl code right here!

(I'm not sure what you mean by "initial install step", though)

**Comment by amasad** [comment]
@ljharb sadly, we don't currently have a way to clone a git subtree. I think it'd be pretty trivial to maintain a separate repo like this one: https://github.com/amasad/enzyme-playground/

Or simply keep the code in repl.it without necessarily having any backing repo.

**Comment by ljharb** [comment]
There's administrative overhead right now in having a separate repo, so that's not an option.

I'm fine keeping the code in repl.it as well - if i forked yours, and used my fork as the base, would that work? (Separately, i tried to sign up but it wants read and write access to all my public and private repos, which is way too broad for me to be able to use the service)

**Comment by amasad** [comment]
Yes, forking works. 

Feel free to sign up with Google or email right now as you don't need the GitHub permissions. That's good feedback though -- the reason we ask for them is that people bring in their repos and commit/push to them. But we can probably do it on demand.

**Comment by ljharb** [comment]
If i sign up with google or email, can i merge it with my github credentials later?

**Comment by amasad** [comment]
>If i sign up with google or email, can i merge it with my github credentials later?

Yes. Once you decide to commit push back to GitHub you can authenticate with GitHub. Also you can manage "connected services" under your account https://repl.it/account

**Comment by ljharb** [comment]
@amasad turns out i can't change my username after signing up with google :-(

**Comment by amasad** [comment]
@ljharb that's dumb -- we'll fix it! I'll change it for you. What's your current username?

**Comment by ljharb** [comment]
@amasad JordanHarband, i'd prefer it be LJHarb

**Comment by amasad** [comment]
Done! https://repl.it/@LJHarb

**Comment by amasad** [comment]
@ljharb Done! https://repl.it/@LJHarb

**Pull request closed without merging**
