### PR TITLE
Add HOCComponent case to 'toTree' function.

### PR DESCRIPTION
**Pull request by psr1919plus21**
Hi!
I write several tests for my component and it's work fine, but when I wrapped my component with some HOC that create function like this:

```
function Foo(props) {
                var _this = _super.call(this, props) || this;
                _this.action = _this.action.bind(_this);
                _this.nodeParams = __assign({}, nodeParams, props.logNode, { events: __assign({}, nodeParams.events, (props.logNode && props.logNode.events)) });
                return _this;
}
```

I faced with error: `Enzyme Internal Error: unknown node with tag 9`.

I add code for this case to `enzyme-adapter-react-16.2` because I have `"enzyme-adapter-react-16": "1.2.0",` in my `package.json` file.

Not sure about that I need to add similar changes for other versions.

1. Can you approve my changes?
2. Can you help me with understanding about other adapter versions?
3. How else I can help? What kind of information I need to provide additionally?

Thanks :)

### CODE REVIEW

**Comment by ljharb** [comment]
Also, `this` in a function component makes no sense - they shouldn’t have one.

**Comment by psr1919plus21** [comment]
Thanks for answer

I use `"react": "16.8.4"`
`this` in a function component utilizes for logs purposes.

If we talk out of context of my HOC component, it's good idea to handle this case?
Should I use `ContextConsumer` constant and add some regression tests?

**Comment by ljharb** [comment]
React passes `this` as `undefined` (or the global object) to function components, so there's no logging value to be had.

If you're using React 16.4, then changing the 16.2 adapter doesn't seem productive. Can you share more of your code? Specifically, the untranspiled code?

**Comment by ljharb** [comment]
@psr1919plus21 is this PR something you're still interested in completing?

**Comment by ljharb** [comment]
Happy to reopen if there's still value to be had here; closing for now.

**Pull request closed without merging**
